### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hugovk** [brandonramirez/grunt-jsonlint#13]
Running on ~275k geojson files I get this:

```
E:\data>grunt
Running "jsonlint:sample" (jsonlint) task
Warning: Maximum call stack size exceeded Use --force to continue.

Aborted due to warnings.
```

Is there any way around this?

**Comment by brandonramirez** [comment]
Can you share an example for me to test/debug against?

**Comment by hugovk** [comment]
See the lint branch of this repo: https://github.com/hugovk/whosonfirst-data/tree/lint

Something like this:
```
git clone https://github.com/hugovk/whosonfirst-data.git # takes up nearly 5 GB on disk!

cd whosonfirst-data
git checkout lint
grunt
```

This is with Grunt 0.4.5 on Windows 7.

I also ran it on Travis CI, which errored due to it listing all the files:
```
Running "jsonlint:sample" (jsonlint) task
Verifying property jsonlint.sample exists in config...OK
Files: data/0/0.geojson, data/101/711/873/101711873.geojson, data/101/711/875/101711875.geojson, data/101/711/877/101711877.geojson, data/101/711/879/101711879.geojson, <snip>

The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

The build has been terminated.
```

https://travis-ci.org/hugovk/whosonfirst-data/builds/77278471
https://s3.amazonaws.com/archive.travis-ci.org/jobs/77278472/log.txt

---

In the second commit, I added [quiet-grunt](https://github.com/bahmutov/quiet-grunt) to see if it makes a difference, but I get the same error on my machine:

```
E:\data>grunt
....
Running "jsonlint:sample" (jsonlint) task
Warning: Maximum call stack size exceeded Use --force to continue.

Aborted due to warnings.
```

 and Travis still errors in the same way after logging all the filenames:

https://travis-ci.org/hugovk/whosonfirst-data/builds/77280718
https://s3.amazonaws.com/archive.travis-ci.org/jobs/77280719/log.txt

**Comment by brandonramirez** [comment]
The problem appears to be `grunt`, not `jsonlint` or the `grunt-jsonlint` plugin.

Somewhere in the `data` directory, you have a directory structure so incredibly deep that it when Grunt walks it recursively (due to the `**` token in the `Gruntfile`), it overflows the call stack trying to collect the list of files.

**Comment by brandonramirez** [comment]
Look at this Gruntfile I created based off yours: https://gist.github.com/brandonramirez/cda6455d05c9abf7f1ad

I added a 'nada' task whose purpose is to do nothing except confirm that a task can be run successfully, including expanding the glob pattern.

I can reproduce the problem with just that task:

virago:whosonfirst-data brandon$ grunt nada
.....
Running "nada:sample" (nada) task
sample: Successfully ran nada.
Warning: Maximum call stack size exceeded Use --force to continue.

Aborted due to warnings.
virago:whosonfirst-data brandon$

Interestingly, the `sample: Successfully ran nada.` message prints out.  It appears that Grunt does not process the source file mapping until we retrieve it by accessing `filesSrc`.  Accessing it via `files` does not trigger the call stack overflow.

I'll experiment with the source in `grunt-jsonlint` to see if we can request the file list from Grunt through a different way which doesn't have this problem (see previous paragraph).  However, given the recursive nature of directory structures, I'm not optimistic.

**Comment by brandonramirez** [comment]
Walking the directory structure does not appear to be the problem after all.  It's something within Grunt's algorithm for building `filesSrc`.

I've made a temporary change to Grunt directly and it runs without error.  Though it took an extremely long time to lint all of those files.

    $ grunt jsonlint
    Running "jsonlint:sample" (jsonlint) task
    >> 273743 files lint free.

    Done, without errors.
    $

**Comment by hugovk** [comment]
@brandonramirez Thank you very much for investigating this so thoroughly! 

Roughly how long is "an extremely long time"? My idea was to run this on Travis CI to help for PRs, so it doesn't really matter too much how long it takes, as long as it's within Travis's ~10 minute timeout.

**Comment by brandonramirez** [comment]
It was over an hour.  I let it run overnight and it was finished when I woke up, so I didn't measure it.  But it was on the order of hours, not minutes.

It's not clear yet if that time was spent discovering the files to lint or linting then.

**Comment by brandonramirez** [comment]
I reran it again overnight.  It took 160 minutes to lint 273,743 JSON files.

**Comment by hugovk** [comment]
Thanks. I think I'll look for a way just to check recently changed/committed files.

**Comment by brandonramirez** [comment]
I traced the problem to a problem with the `flatten` function in the older version of lodash Grunt is internally using to normalize the file lists given in the Gruntfile.

If you're curious, this stackoverflow answer explains it:

http://stackoverflow.com/a/22123980/1649198

What took me forever to wrap my head around is the flatten is in fact a recursive function and the error you are seeing usually happens when there is infinite recursion.  But in this case, that was not it at all.  `apply` is being used to flatten an array into a list of parameters and that list is too large for the JavaScript runtime.

I looked at the latest version of `flatten` in lodash and I think the problem is solved (I haven't tested it).  I will recommend to the Grunt team that they upgrade lodash.

How urgently do you need this working?  I may be able to work-around this temporarily within `grunt-jsonlint`.

**Comment by hugovk** [comment]
It's not urgent, let's wait on Grunt. Thanks again for following this through!
