### ISSUE TITLE
Update error detection for json

### ISSUE THREAD

**Issue by paladox** [brandonramirez/grunt-jsonlint#21]
Hi thanks for adding this support but could the whole line be shown instead of halve off it. Please do it similar to what jscs or jshint does. They also have grunt plugins.

Also the line detection is not accurate since 

>> File "i18n/en.json" failed JSON validation at line 15. says that and then

Warning: Parse error on line 16: says that.

The accurate one is Warning: Parse error on line 16: not >> File "i18n/en.json" failed JSON validation at line 15. says that and then

**Comment by HolgerJeromin** [comment]
BTW: The >> is coming from grunt. The corresponding issue has a PR (from me :-) open 
https://github.com/gruntjs/grunt-legacy-log/issues/5

**Comment by brandonramirez** [comment]
Can you provide steps to reproduce the "half-line" issue?  It appears to show the entire line for me.  The line number and the error message both come from the underlying jsonlint package.  I'll look into more flexible error reporting options.  We are able to extract some raw details of the error, even though today we only echo the error.  But it is a slippery slope where we could become so customizable that the time to setup grunt-jsonlint will be overwhelming.

**Comment by brandonramirez** [comment]
I looked at how `grunt-contrib-jshint` reports errors and it's definitely nice.  I'll see what I can do, but I need to be careful because I have different requests for formats.

**Comment by paladox** [comment]
@brandonramirez ok, thanks for looking into this.

**Comment by brandonramirez** [comment]
@paladox I reviewed how `grunt-contrib-jshint` and the underlying `jshint` library work for error reporting.

The key to the beautiful output is that they group the errors by file, showing each error in each file.  The problem here is that `jsonlint` stops at the first error.

To get all errors, we would need to make heavy, complex changes to the `jsonlint` library, which appears to be no longer maintained by its author.

I do have an improvement to make it similar to `jshint`, however.  I don't want to commit to it, so I'll make the output configurable.

**Comment by paladox** [comment]
Thankyou.
